"""Add preferences and opportunities tables

Revision ID: 1c8179753437
Revises: 8b1e1948c7b8
Create Date: 2026-01-24 20:57:21.434517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8179753437'
down_revision: Union[str, Sequence[str], None] = '8b1e1948c7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opportunity_type', sa.Enum('INTERNSHIP', 'JOB', 'PROJECT', 'HACKATHON', 'RESEARCH', 'OTHER', name='opportunitytype'), nullable=True),
    sa.Column('in_house', sa.Boolean(), nullable=True),
    sa.Column('opportunity_image', sa.String(), nullable=True),
    sa.Column('opportunity_description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('opportunity_uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_frequency', sa.Enum('DAILY', 'WEEKLY', 'NONE', name='emailfrequency'), nullable=True),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('preferred_days', sa.String(), nullable=True),
    sa.Column('reminder_types', sa.String(), nullable=True),
    sa.Column('days_before_deadline', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
